spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_data_jpa
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true